### ISSUE TITLE
Toggle the visibility of the process list on and off

### ISSUE THREAD

**Issue by Josharias** [Terasology/Machines#8]
I want to be able to toggle the process list off (and then back on again) so that those that do not like the clutter can have their screen back.
- persist this setting per player

**Comment by jdrueckert** [comment]
My assumption is that the "process list" is some UI screen related to machines which shows running "processes".
If this is correct, we need to find out which screen is meant here, then this should be a relatively easy change.
If my assumption is incorrect, the only "process list" I can think of is related to our in-game debug information which afaik can already be toggled, rendering this issue done.

**Comment by jdrueckert** [comment]
Watching [this video](https://www.youtube.com/watch?v=XYn-SIZ6Fyw), I now think the following "recipe" list on the side is what was referenced as "process list" here:
![image](https://user-images.githubusercontent.com/29981695/166120200-9af1e0d1-ea27-47aa-9581-d02c55aae457.png)

As this no longer exists and the recipes are accessible via the item help, I don't think this issue is relevant anymore.
